version: "3"

services:
  todo:
    build: .
    ports:
      - "3769:9285"
    depends_on:
      - postgres
      - mongo
    networks:
      - todo_net

  postgres:
    image: theshultz/kaplat-postgres-instance
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=todos
    networks:
      - todo_net
  
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    # volumes:
    #   - mongo_data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    # image: theshultz/kaplat-mongo-instance
    # command: ['--logpath', '/var/mongo.log']
    # ports:
    #   - "27017:27017"
    networks:
      - todo_net
  
networks:
  todo_net:
    name: todo_net